<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE PROFILE [<!ELEMENT PROFILE (SECTION*)><!ELEMENT SECTION (KEYVALPAIR*)><!ATTLIST SECTION NAME CDATA "" ><!ELEMENT KEYVALPAIR (#PCDATA)><!ATTLIST KEYVALPAIR KEY CDATA "" VAL CDATA "" >]>
<PROFILE><SECTION NAME="AUTOSAR_XML"><KEYVALPAIR KEY="DataTypeInvalidValueWithinRange" VAL="1"/><KEYVALPAIR KEY="ExtendedShortNameLength" VAL="1"/><KEYVALPAIR KEY="SyncAliveTimeout" VAL="1"/></SECTION><SECTION NAME="CHECK_AND_SYNCHRONIZE"><KEYVALPAIR KEY="BlueprintCompliance" VAL="1"/><KEYVALPAIR KEY="DataMapping_Compatibility" VAL="1"/><KEYVALPAIR KEY="DataMapping_Defines" VAL="1"/><KEYVALPAIR KEY="DataMapping_InitValues" VAL="1"/><KEYVALPAIR KEY="DataMapping_InvalidValues" VAL="1"/><KEYVALPAIR KEY="DataMapping_Length" VAL="1"/><KEYVALPAIR KEY="DataMapping_Scale" VAL="1"/><KEYVALPAIR KEY="DataMapping_Unit" VAL="1"/><KEYVALPAIR KEY="DataTypeMapping_MissingAppImplMap" VAL="1"/><KEYVALPAIR KEY="DataType_UseTerminatingNullByteForStrings" VAL="1"/><KEYVALPAIR KEY="DifferentBlueprintDefinitions" VAL="1"/><KEYVALPAIR KEY="E2EConsistency" VAL="1"/><KEYVALPAIR KEY="PortCompat_CheckDelegationConnectorComSpec" VAL="1"/><KEYVALPAIR KEY="PortGroupConsistency" VAL="1"/><KEYVALPAIR KEY="PortInterfaceMapping_InconsistentTexttables" VAL="1"/><KEYVALPAIR KEY="PortInterfaceMapping_UnmappedDataPrototypes" VAL="1"/><KEYVALPAIR KEY="PortPrototypeBPWithoutPortInterface" VAL="1"/><KEYVALPAIR KEY="SoftwareDesign_PortCompatibility" VAL="0"/><KEYVALPAIR KEY="UnconnectedPorts_Calibration" VAL="1"/><KEYVALPAIR KEY="UnconnectedPorts_ClientPorts" VAL="1"/><KEYVALPAIR KEY="UnconnectedPorts_NvM" VAL="1"/><KEYVALPAIR KEY="UnconnectedPorts_ReceiverPorts" VAL="1"/><KEYVALPAIR KEY="UnconnectedPorts_SenderPorts" VAL="1"/><KEYVALPAIR KEY="UnconnectedPorts_ServerPorts" VAL="1"/><KEYVALPAIR KEY="UnusedDE_Requires_InitVals" VAL="1"/><KEYVALPAIR KEY="UnusedDataElements" VAL="1"/></SECTION><SECTION NAME="DEFAULT_BLUEPRINTS"><KEYVALPAIR KEY="Default_BlueprintMappingSet" VAL=""/></SECTION><SECTION NAME="DEFAULT_MAPPINGSETS"><KEYVALPAIR KEY="Default_PortInterfaceMappingSet" VAL=""/></SECTION><SECTION NAME="DEFAULT_PACKAGES"><KEYVALPAIR KEY="DefaultPackage_BaseTypes" VAL="DataTypes/BaseTypes"/><KEYVALPAIR KEY="DefaultPackage_BlueprintMappingSets" VAL="Blueprints/BlueprintMappingSets"/><KEYVALPAIR KEY="DefaultPackage_Blueprints" VAL="Blueprints/PortPrototypeBlueprints"/><KEYVALPAIR KEY="DefaultPackage_ComponentTypes" VAL="ComponentTypes"/><KEYVALPAIR KEY="DefaultPackage_CompuMethods" VAL="DataTypes/CompuMethods"/><KEYVALPAIR KEY="DefaultPackage_Constants" VAL="Constants"/><KEYVALPAIR KEY="DefaultPackage_DataConstrs" VAL="DataTypes/DataConstrs"/><KEYVALPAIR KEY="DefaultPackage_DataTypeMappingSets" VAL="ComponentTypes/DataTypeMappingSets"/><KEYVALPAIR KEY="DefaultPackage_DataTypes" VAL="DataTypes"/><KEYVALPAIR KEY="DefaultPackage_ECUCompositionTypes" VAL="ECUCompositionTypes"/><KEYVALPAIR KEY="DefaultPackage_ECUCompositions" VAL="ECUCompositions"/><KEYVALPAIR KEY="DefaultPackage_ECUProjects" VAL="Systems"/><KEYVALPAIR KEY="DefaultPackage_EndToEndProtections" VAL="EndToEndProtections"/><KEYVALPAIR KEY="DefaultPackage_ModeDeclarationGroups" VAL="ModeDclrGroups"/><KEYVALPAIR KEY="DefaultPackage_PortInterfaces" VAL="PortInterfaces"/><KEYVALPAIR KEY="DefaultPackage_Units" VAL="DataTypes/Units"/></SECTION><SECTION NAME="GENERATOR"><KEYVALPAIR KEY="GeneratorOutputPath" VAL="$(InstallDir)\Output\"/><KEYVALPAIR KEY="SWCGeneratorPath" VAL="$(InstallDirBin)\DVSwcGen.exe"/><KEYVALPAIR KEY="UseSIPGenerator" VAL="0"/></SECTION><SECTION NAME="GRAPHIC_OBJECT_FILTER"><KEYVALPAIR KEY="ShowCalibrationObjects" VAL="1"/><KEYVALPAIR KEY="UseGraphicEditors" VAL="1"/></SECTION><SECTION NAME="IMEX_XML_SETTINGS"><KEYVALPAIR KEY="CheckDifferencesBeforeImport" VAL="0"/><KEYVALPAIR KEY="DoConsistenceCheckAfterImport" VAL="1"/><KEYVALPAIR KEY="FindUnusedElementsafterImport" VAL="0"/><KEYVALPAIR KEY="ImportModePresetForCreated" VAL="0"/><KEYVALPAIR KEY="IncrementArraySize" VAL="1"/><KEYVALPAIR KEY="KeepUUID" VAL="0"/><KEYVALPAIR KEY="LockCreatedObjects" VAL="1"/><KEYVALPAIR KEY="MergeElementsFromDifferentPackagesDuringImport" VAL="0"/><KEYVALPAIR KEY="PackageImport" VAL="1"/><KEYVALPAIR KEY="PackageImport_AR4" VAL="1"/><KEYVALPAIR KEY="ReplaceLegacyTypes" VAL="0"/><KEYVALPAIR KEY="SubstituteMissingObjects" VAL="0"/><KEYVALPAIR KEY="UseImportModePreset" VAL="0"/><KEYVALPAIR KEY="UseImportModePresetForCreated" VAL="0"/></SECTION><SECTION NAME="MISC"><KEYVALPAIR KEY="DeleteUnreferencedDCFFiles" VAL="1"/><KEYVALPAIR KEY="EnableDataTransformation" VAL="0"/><KEYVALPAIR KEY="UseE2EXf" VAL="0"/></SECTION></PROFILE>
